//! Reads databases produced by the real `sqlite3` program.
//!
//! Unit tests can only show the reader is self-consistent. These read files
//! that SQLite itself wrote, which is the only evidence that the byte layout
//! is actually compatible.
//!
//! The fixtures are generated by `tools/gen_interop.sh`, which runs the real
//! `sqlite3` binary and records the expected rows alongside each file.

use std::path::{Path, PathBuf};

use nsqlite::btree::TableBtree;
use nsqlite::pager::Pager;
use nsqlite::value::Value;

/// The fixtures directory, overridable so the test can be run from anywhere.
fn fixture_dir() -> PathBuf {
    match std::env::var("NSQLITE_INTEROP_DIR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../test/interop")
            .to_path_buf(),
    }
}

/// Returns the fixture directory if it has been generated, so the tests skip
/// cleanly on a machine without the `sqlite3` binary.
fn require_fixtures() -> Option<PathBuf> {
    let dir = fixture_dir();
    if dir.join("basic.db").exists() {
        Some(dir)
    } else {
        None
    }
}

/// Opens a database file with the pager.
fn open(path: &Path) -> Pager {
    Pager::open(path).unwrap_or_else(|e| panic!("opening {}: {e}", path.display()))
}

/// Finds a table's root page by reading `sqlite_schema`.
///
/// The schema table is always a table b-tree rooted at page 1, with columns
/// (type, name, tbl_name, rootpage, sql) and the rowid equal to the index in
/// the schema, so this also exercises the record reader on real bytes.
fn root_page_of(pager: &mut Pager, table: &str) -> u32 {
    let mut schema = TableBtree::new(pager, 1);
    let rows = schema.scan().expect("reading sqlite_schema");
    for row in rows {
        // type, name, tbl_name, rootpage, sql
        if row.values.len() < 4 {
            continue;
        }
        let kind = row.values[0].as_str().unwrap_or("");
        let name = row.values[1].as_str().unwrap_or("");
        if kind == "table" && name.eq_ignore_ascii_case(table) {
            return row.values[3].as_i64().unwrap_or(0) as u32;
        }
    }
    panic!("table {table} not found in sqlite_schema");
}

#[test]
fn reads_a_schema_written_by_real_sqlite() {
    let Some(dir) = require_fixtures() else {
        return;
    };
    let mut pager = open(&dir.join("basic.db"));
    let root = root_page_of(&mut pager, "t");
    assert!(root >= 2, "a user table cannot live on page 1");

    let mut t = TableBtree::new(&mut pager, root);
    let rows = t.scan().expect("scanning t");
    assert_eq!(rows.len(), 4, "the fixture has four rows");

    // (id INTEGER PRIMARY KEY, name TEXT, score REAL, data BLOB)
    // The INTEGER PRIMARY KEY is a rowid alias, so it is stored as NULL in the
    // record and recovered from the key.
    let expected: &[(i64, &str, Option<f64>, Option<&[u8]>)] = &[
        (-5, "negative", Some(-3.5), Some(&[0x01])),
        (1, "alpha", Some(1.5), Some(&[0xAA, 0xBB])),
        (2, "beta", Some(2.25), None),
        (3, "gamma", None, Some(&[0x00, 0xFF, 0x00])),
    ];
    for (row, (rowid, name, score, data)) in rows.iter().zip(expected) {
        assert_eq!(row.rowid, *rowid, "rowid mismatch");
        // Column 0 is the IPK alias: stored as NULL, read from the key.
        assert_eq!(row.values[0], Value::Null, "the IPK slot is stored as NULL");
        assert_eq!(
            row.values[1].as_str(),
            Some(*name),
            "text mismatch for rowid {rowid}"
        );
        match score {
            Some(s) => assert_eq!(row.values[2].as_f64(), Some(*s), "real mismatch at {rowid}"),
            None => assert_eq!(row.values[2], Value::Null, "expected NULL real at {rowid}"),
        }
        match data {
            Some(b) => assert_eq!(
                row.values[3].as_blob(),
                Some(*b),
                "blob mismatch at {rowid}"
            ),
            None => assert_eq!(row.values[3], Value::Null, "expected NULL blob at {rowid}"),
        }
    }
}

#[test]
fn reads_an_empty_table() {
    let Some(dir) = require_fixtures() else {
        return;
    };
    let mut pager = open(&dir.join("empty.db"));
    let root = root_page_of(&mut pager, "e");
    let mut t = TableBtree::new(&mut pager, root);
    assert!(t.scan().unwrap().is_empty());
    assert_eq!(t.max_rowid().unwrap(), 0);
}

#[test]
fn reads_a_row_that_spills_into_overflow_pages() {
    let Some(dir) = require_fixtures() else {
        return;
    };
    let mut pager = open(&dir.join("bigrow.db"));
    let root = root_page_of(&mut pager, "big");
    let mut t = TableBtree::new(&mut pager, root);
    let rows = t.scan().expect("scanning the spilling table");
    assert_eq!(rows.len(), 1);
    let text = rows[0].values[0].as_str().expect("a text value");
    // The fixture is 20000 hex digits, so a mis-ordered or dropped overflow page
    // shows up as a content mismatch rather than only a length mismatch.
    assert_eq!(text.len(), 20_000, "the whole payload must come back");
    assert!(text.bytes().all(|b| b.is_ascii_hexdigit()));
}

#[test]
fn reads_many_rows_across_several_leaf_pages() {
    let Some(dir) = require_fixtures() else {
        return;
    };
    let mut pager = open(&dir.join("manyrows.db"));
    let root = root_page_of(&mut pager, "many");
    let mut t = TableBtree::new(&mut pager, root);

    // More rows than fit on one page, so the tree has interior pages and the
    // left-to-right leaf walk has to visit several of them.
    let pages = t.leaf_pages().unwrap();
    assert!(pages.len() > 1, "the fixture should span multiple leaves");

    let rows = t.scan().expect("scanning");
    assert_eq!(rows.len(), 5_000);
    // Rowids must come back in key order, which is what the interior pages
    // encode; a broken child order would show up here as a non-monotonic scan.
    for (i, row) in rows.iter().enumerate() {
        assert_eq!(
            row.rowid,
            i as i64 + 1,
            "rows must be in ascending rowid order"
        );
    }
    assert_eq!(t.min_rowid().unwrap(), 1);
    assert_eq!(t.max_rowid().unwrap(), 5_000);
    // Spot-check that a lookup by key finds the right row. Column 0 holds the
    // integer, column 1 its text label.
    let found = t.find(2_500).unwrap().expect("rowid 2500 must exist");
    assert_eq!(found.values[0], Value::Integer(2_500));
    assert_eq!(found.values[1], Value::Text("row2500".into()));
    assert!(t.find(5_001).unwrap().is_none());
}

#[test]
fn reads_a_rowid_table_with_negative_rowids() {
    let Some(dir) = require_fixtures() else {
        return;
    };
    let mut pager = open(&dir.join("negatives.db"));
    let root = root_page_of(&mut pager, "n");
    let mut t = TableBtree::new(&mut pager, root);
    let rows = t.scan().unwrap();
    // A rowid is signed; the varint stores the raw bit pattern, so this is
    // where a naive unsigned decode would corrupt every negative key.
    let ids: Vec<i64> = rows.iter().map(|r| r.rowid).collect();
    assert_eq!(ids, vec![-9_223_372_036_854_775_808, -1000, -1, 0, 1]);
}

#[test]
fn reads_every_storage_class_from_a_real_file() {
    let Some(dir) = require_fixtures() else {
        return;
    };
    let mut pager = open(&dir.join("types.db"));
    let root = root_page_of(&mut pager, "ty");
    let mut t = TableBtree::new(&mut pager, root);
    let rows = t.scan().unwrap();

    let by_name = |n: &str| -> Value {
        rows.iter()
            .find(|r| r.values[0].as_str() == Some(n))
            .unwrap_or_else(|| panic!("row {n} missing"))
            .values[1]
            .clone()
    };
    assert_eq!(by_name("null"), Value::Null);
    assert_eq!(by_name("zero"), Value::Integer(0));
    assert_eq!(by_name("one"), Value::Integer(1));
    assert_eq!(by_name("small"), Value::Integer(-128));
    assert_eq!(by_name("medium"), Value::Integer(140_737_488_355_327));
    assert_eq!(by_name("max"), Value::Integer(i64::MAX));
    assert_eq!(by_name("min"), Value::Integer(i64::MIN));
    assert_eq!(by_name("real"), Value::real(std::f64::consts::PI));
    assert_eq!(by_name("negreal"), Value::real(-0.5));
    assert_eq!(by_name("text"), Value::Text("héllo wörld".into()));
    assert_eq!(by_name("empty"), Value::Text(String::new()));
    assert_eq!(by_name("blob"), Value::Blob(vec![0, 1, 2, 254, 255]));
    assert_eq!(by_name("emptyblob"), Value::Blob(Vec::new()));
    // SQLite stores a REAL NaN as NULL, on both the write and the read side.
    assert_eq!(by_name("nan"), Value::Null);
}
